language: objective-c

before_install:
  - brew update
  
install:
  - mkdir -p $(brew --repo)/Library/Taps/osrf
  - ln -s $PWD $(brew --repo)/Library/Taps/osrf/homebrew-simulation
  - brew tap --repair
  
script:
  - brew audit $(brew --repo)/Library/Taps/osrf/homebrew-simulation/*.rb
  
matrix:
  fast_finish: true
